[config]
reload_apps = true
set_wallpaper = true
wallpaper_tool = 'Swww'
swww_options = [
    "--transition-fps",
    "120",
    "-t",
    "wave"
]

# Mako 模板
[templates.mako]
input_path = '~/.config/matugen/templates/mako/config'
output_path = '~/.config/mako/config'

# Hypr 模板
[templates.hypr]
input_path = '~/.config/matugen/templates/hypr/colors.conf'
output_path = '~/.config/hypr/colors.conf'

# Rofi 模板
[templates.rofi]
input_path = '~/.config/matugen/templates/rofi/config.rasi'
output_path = '~/.config/rofi/config.rasi'

# Waybar 模板
[templates.waybar]
input_path = '~/.config/matugen/templates/waybar/colors.css'
output_path = '~/.config/waybar/colors.css'

# Foot 模板
[templates.foot]
input_path = '~/.config/matugen/templates/foot/foot.ini'
output_path = '~/.config/foot/foot.ini'

# Waylyrics 模板
[templates.waylyrics]
input_path = '~/.config/matugen/templates/waylyrics/theme.css'
output_path = '~/.local/share/waylyrics/_themes/material_you.css'

# Cava 模板
[templates.cava]
input_path = '~/.config/matugen/templates/cava/config'
output_path = '~/.config/cava/config'

# Dunst 模板
# [templates.dunst]
# input_path = '~/.config/matugen/templates/dunst/style.css'
# output_path = '~/.config/matugen/templates/dunst'
